### ISSUE TITLE
checksums did NOT match

### ISSUE THREAD

**Issue by firekcc** [jeanblanchard/docker-java#12]
I build the docker images across the problem，the error is as follows

**sha256sum: WARNING: 1 of 1 computed checksums did NOT match
java.tar.gz: FAILED**

Could it be that oracle jave does not support curl or wget downloads

**Comment by jeanblanchard** [comment]
Well, it appears that, following the Oracle JDK license change in April 2019, you can no longer download a JDK from Oracle's website without logging in to an Oracle Account. Anyway with the new license, it doesn't make much sense any more to repackage an Oracle JDK, since you're not supposed to use it in production.

Sooo. I guess this marks the end of this image, and it's time to move on to alternatives. When I have a minute, I'll update the README with pointers to alternatives. On the top of my head I can think of:
* `openjdk` (Oracle OpenJDK) - No alpine tags for stable releases
* `adoptopenjdk/openjdk8` / `adoptopenjdk/openjdk11` (AdoptOpenJDK) - Seems to have Alpine tags, but I haven't tested yet - I use AdoptOpenJDK to develop outside containers, though.
* `gcr.io/distroless/java` (from Google Container Tools) - Minimal OS based on libc - not Alpine - this is what I use on projects where I have no requirements on the underlying OS, building the image with Jib.
