### ISSUE TITLE
support Java 9

### ISSUE THREAD

**Issue by gzm55** [jeanblanchard/docker-java#7]
Hi, is it time for moving to java 9 release?

**Comment by jeanblanchard** [comment]
Hi. Yes I'll look into it.
I can't reuse directly what I did for Java 9 Early Access, or the existing Java 8 code. It'll will take some testing to get this working while keeping a decent amount of files cleanup.

Also I'll probably not make Java 9 the default for a while, considering how many project will probably break with the modules...

**Comment by gzm55** [comment]
OK, from [Oracle EOL]( http://www.oracle.com/technetwork/java/eol-135779.html ), java 9/18.3 are neither LTS. so the default one could be the latest LTS release (jdk8 --> jdk18.9).

**Comment by gzm55** [comment]
hi @jeanblanchard , any updates?

**Comment by jeanblanchard** [comment]
Yeah, I'm actually not sure if I should continue maintaining this image for Java 9.

It would be probably better to simply redirect users to the official OpenJDK image, especially since there is an alpine variant.

There are less and less differences between OpenJDK and Oracle JDK. OpenJDK is the reference implementation.

If anyone gives me good reasons to support Oracle JDK over OpenJDK, I would gladly reconsider, of course...

**Comment by jeanblanchard** [comment]
Oh wait, there is actually no openjdk alpine image for java 9, only 7 and 8. Maybe they could not get it to work either.

**Comment by gzm55** [comment]
To get it work, many similar images are using ea builds of musl version jdk9 (project Portola [0]), such as [1], [2].

--
[0] http://openjdk.java.net/projects/portola/
[1] https://github.com/anapsix/docker-alpine-java/blob/java9/9/0b0/jdk9/standard/Dockerfile
[2] https://github.com/jfisbein/alpine-oracle-jdk9/blob/master/Dockerfile
